### ISSUE TITLE
Waline评论未正常工作

### ISSUE THREAD

**Issue by NoctuG** [theme-kaze/hexo-theme-kaze#69]
描述问题：尝试使用Waline评论，但在配置完成后文章评论部分未能如期加载

如何复现：

（1）在Vercel上部署[服务端](https://comment-waline-amber.vercel.app/)成功
（2）在主题配置文件中进行配置
`````yml
#------------------------
# comment config
#------------------------
comment:
  enable: true
  type: waline
 waline:
    serverURL: https://comment-waline-amber.vercel.app/
    placeholder: Just go go
    path: window.location.pathname
    avatar: mp
    meta: ["nick", "mail", "link"]
    pageSize: 10
    visitor: false
    highlight: true
    emojiCDN: https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
    emojiMaps: null
    enableQQ: false
    requiredFields: ["nick"]
    anonymous: true
```````````````````
3. [Demo](https://mlou.vercel.app/2022/06/21/hello-world/)评论部分

使用环境：
 
 - 使用 Hexo 版本：6.2.0
 - 使用主题版本：v1.1.0-beta4
 - 浏览器版本：Microsoft Edge ，版本 102.0.1245.44

额外信息：换用其它评论正常工作

希望作者大大解答一下，谢谢     ：）
